export const DEFAULT_OUTFILE = 'apiful.d.ts' as const

export const GENERATED_FILE_HEADER = `// Generated by \`apiful generate\` – do not edit.\n/* eslint-disable */\n` as const

export const LINT_DISABLE_HEADER = `/* eslint-disable */\n` as const
